Presentation/ASF.UI.WbSite/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASF.Entities;
using ASF.UI.Process;
using ASF.UI.WbSite.Services.Cache;

namespace ASF.UI.WbSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountryController : Controller
    {
        // GET: Country
        public ActionResult Index()
        {
            //var cp = new CountryProcess();
            var lista = DataCache.Instance.CountryList();
            //return View(cp.SelectList());
            return View(lista);
        }

        // GET: Country/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Country/Create
        [HttpPost]
        public ActionResult Create(Country country)
        {
            try
            {
                var cp = new CountryProcess();
                cp.insertCountry(country);
                DataCache.Instance.CountryListRemove();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Country/Details
        public ActionResult Details(int id)
        {
            var cp = new CountryProcess();

            return View(cp.findCountry(id));
        }

        // GET: Country/Edit/5
        public ActionResult Edit(int id)
        {
            var cp = new CountryProcess();

            return View(cp.findCountry(id));
        }

        // POST: Country/Edit/5
        [HttpPost]
        public ActionResult Edit(Country country)
        {
            try
            {
                var cp = new CountryProcess();
                cp.editCountry(country);
                DataCache.Instance.CountryListRemove();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Country/Delete/5
        public ActionResult Delete(int id)
        {
            var cp = new CountryProcess();

            return View(cp.findCountry(id));
        }

        // POST: Country/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Country country)
        {
            try
            {
                var cp = new CountryProcess();
                cp.deleteCountry(id);
                DataCache.Instance.CountryListRemove();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Presentation/ASF.UI.WbSite/Controllers/DealerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASF.Entities;
using ASF.UI.Process;
using ASF.UI.WbSite.Services.Cache;

namespace ASF.UI.WbSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DealerController : Controller
    {
        // GET: Dealer
        public ActionResult Index()
        {
            //var cp = new DealerProcess();
            var lista = DataCache.Instance.DealerListDTO();
            //return View(cp.SelectList());
            return View(lista);
        }

        // GET: Dealer/Create
        public ActionResult Create ()
        {
            var category = new CategoryProcess().SelectList();
            var country = new CountryProcess().SelectList();

            ViewBag.Category = new SelectList(category, "Id", "Name");
            ViewBag.Country = new SelectList(country, "Id", "Name");

            return View();
        }

        // POST: Dealer/Create
        [HttpPost]
        public ActionResult Create(Dealer dealer)
        {
            try
            {
                var cp = new DealerProcess();
                cp.insertDealer(dealer);
                DataCache.Instance.DealerListRemoveDTO();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dealer/Details
        public ActionResult Details (int id)
        {
            var cp = new DealerProcess();
            return View(cp.findDealer(id));
        }

        // GET: Dealer/Edit/5
        public ActionResult Edit (int id)
        {

            var category = new CategoryProcess().SelectList();
            var country = new CountryProcess().SelectList();

            ViewBag.Category = new SelectList( category, "Id", "Name", id );
            ViewBag.Country = new SelectList( country, "Id", "Name", id );

            var cp = new DealerProcess();
            return View(cp.findDealer(id));
        }

        // POST: Dealer/Edit/5
        [HttpPost]
        public ActionResult Edit(Dealer dealer)
        {
            try
            {
                var cp = new DealerProcess();
                cp.editDealer( dealer );
                DataCache.Instance.DealerListRemoveDTO();
                return RedirectToAction( "Index" );
            }
            catch
            {
                return View();
            }
        }

        // GET: Dealer/Delete/5
        public ActionResult Delete ( int id )
        {
            var cp = new DealerProcess();

            return View( cp.findDealer( id ) );
        }

        // POST: Dealer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Dealer dealer)
        {
            try
            {
                var cp = new DealerProcess();
                cp.deleteDealer( id );
                DataCache.Instance.DealerListRemoveDTO();
                return RedirectToAction( "Index" );
            }
            catch
            {
                return View();
            }
        }
    }
}

Presentation/ASF.UI.WbSite/Views/Country/Create.cshtml
@model ASF.Entities.Country

@{
    ViewBag.Title = "Create";
}
@Html.Partial("_Espacio1")
<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.ChangedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ChangedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChangedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.ChangedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ChangedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChangedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@
@Html.Partial("_Espacio2")

Presentation/ASF.UI.WbSite/Views/Country/Delete.cshtml
@model ASF.Entities.Country

@{
    ViewBag.Title = "Delete";
}
@Html.Partial("_Espacio1")
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.HiddenFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.HiddenFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.HiddenFor(model => model.ChangedOn)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.ChangedOn)
        </dd>

        <dt>
            @Html.HiddenFor(model => model.ChangedBy)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.ChangedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
@Html.Partial("_Espacio2")

Presentation/ASF.UI.WbSite/Views/Country/Details.cshtml
@model ASF.Entities.Country

@{
    ViewBag.Title = "Details";
}
@Html.Partial("_Espacio1")
<h2>Details</h2>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChangedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChangedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChangedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChangedBy)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@Html.Partial("_Espacio2")

Presentation/ASF.UI.WbSite/Views/Country/Edit.cshtml
@model ASF.Entities.Country

@{
    ViewBag.Title = "Edit";
}
@Html.Partial("_Espacio1")
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.ChangedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ChangedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChangedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.ChangedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ChangedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChangedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@
@Html.Partial("_Espacio2")

Presentation/ASF.UI.WbSite/Views/Country/Index.cshtml
@model IEnumerable<ASF.Entities.Country>

@{
    ViewBag.Title = "Index";
}
@Html.Partial("_Espacio1")
<h2>Index</h2>
<br/><br />
<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-sm" })
</p>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
            @Html.HiddenFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.HiddenFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.HiddenFor(model => model.ChangedOn)
        </th>
        <th>
            @Html.HiddenFor(model => model.ChangedBy)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        @*<td>
            @Html.HiddenFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.HiddenFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.HiddenFor(modelItem => item.ChangedOn)
        </td>
        <td>
            @Html.HiddenFor(modelItem => item.ChangedBy)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<div class="row">
    @Html.ActionLink("Back to Dealer", "Index", "Dealer")
</div>

@Html.Partial("_Espacio2")